
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Thu Aug 26 18:26:24 CEST 2021
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int PLUSPLUS = 15;
  public static final int CONST = 11;
  public static final int LESSE = 30;
  public static final int CONSTBOOL = 37;
  public static final int LPAREN = 5;
  public static final int GREATER = 27;
  public static final int SEMI = 10;
  public static final int LESS = 29;
  public static final int MINUS = 21;
  public static final int STAR = 17;
  public static final int RPAREN = 6;
  public static final int AND = 32;
  public static final int OR = 31;
  public static final int COMMA = 9;
  public static final int PLUS = 20;
  public static final int IF = 23;
  public static final int EOF = 0;
  public static final int MINUSMINUS = 16;
  public static final int EQUAL = 12;
  public static final int NEW = 22;
  public static final int error = 1;
  public static final int DASH = 18;
  public static final int PERCENT = 19;
  public static final int GREATERE = 28;
  public static final int NUMBER = 34;
  public static final int IDENT = 35;
  public static final int VOID = 36;
  public static final int EQU = 25;
  public static final int LBRACE = 3;
  public static final int ELSE = 24;
  public static final int LSQUARE = 7;
  public static final int READ = 13;
  public static final int RSQUARE = 8;
  public static final int NOTEQU = 26;
  public static final int RBRACE = 4;
  public static final int PROG = 2;
  public static final int CONSTCHAR = 33;
  public static final int PRINT = 14;
}

